### ISSUE TITLE
How to combine conan and cmake to cross compile?

### ISSUE THREAD

**Issue by zuowanbushiwo** [madduci/moderncpp-project-template#4]
Hi  madduci:
Thank you very much, I have followed a lot of your projects, about docker msvc, cmake and conan.
What should I do if I want to use this project on the android/MacOS platform? Are there some good reference examples for conan  with cmake  for crossbuild, when the CMakelist have  find_package() or pkg_check_module()  function？ Ex：find_package(OpenSSL REQUIRED) or pkg_check_module(ZLIB zlib REQUIRED)。

For MacOS :
[Dockerfile ](https://github.com/nephatrine/docker-nxbuilder/blob/darwin/Dockerfile)
[CMakeToolChain ](https://github.com/nephatrine/docker-nxbuilder/tree/darwin/override/opt/toolchains)
[Docker image](https://hub.docker.com/layers/nephatrine/nxbuilder/darwin/images/sha256-9f2179479e283eddd3d54eb01b7ace9a0980605c2cc8addcd4f8715a8d469f51?context=explore)

For Android 
[Dockerfile](https://github.com/nephatrine/docker-nxbuilder/blob/android/Dockerfile) 
[CMakeToolChain](https://github.com/nephatrine/docker-nxbuilder/tree/android/override/opt/toolchains) 
[Docker image] (https://hub.docker.com/layers/nephatrine/nxbuilder/android/images/sha256-d13f4af8e8a5ee1be6f57566648339f63ecd05413f10a0125dff0eea06de8a1a?context=explore)

He also has a msvc [dockerfile](https://github.com/nephatrine/docker-nxbuilder/blob/windows/Dockerfile.msvc) which is somewhat different from your docker-msvc-cpp. It is based on [cmake's cross tool chain](https://github.com/nephatrine/docker-nxbuilder/blob/windows/override/opt/toolchains/windows-x86_64-msvc.cmake) configuration. Yours is directly compiled into the windows virtual environment of wine, so DCMAKE_TOOLCHAIN_FILE is not needed. ,Is that right?

best regards

**Comment by madduci** [comment]
Hi

thanks for your kind words. I haven't tested this project myself on MacOS or Android Platform, since i don't own a Mac and I don't have experience with Android NDK toolkit, but I believe it should still work out of the box, especially if you can install the latest conan and CMake versions. The only addition that you should make is to write a CMake Toolchain file yourself and provide it in the CMake configuration (usually with `cmake -DCMAKE_TOOLCHAIN_FILE=file.cmake ..`).

My [docker-msvc-cpp](https://github.com/madduci/docker-msvc-cpp) image uses as entrypoint the wine environment, emulating the CMD terminal, so you won't need a specific CMake Toolchain file, since it is running conan and CMake for windows under wine (together with MSVC)

**Comment by zuowanbushiwo** [comment]
thanks.
